### ISSUE TITLE
Ref to Syslog

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#36]
The syslog server certainly proves to be a good model for T+, but, I'm not sure we can actually reference it to provide the fingerprinting format? (i.e. should we actually couple T+ to Syslog RFC)?

**Comment by haussli** [comment]
I expect that the WG will tell us if this is unacceptable.  I thought that there was no point to duplicating the text in another RFC, since it would be just that, a duplicate.  It also doubles as attribution of the format.

There may be another source of that same format description, that is syslog may have duplicated it from somewhere, but I did not locate another source among RFCs.

**Comment by haussli** [comment]
I asked Warren for his opinion about referencing other RFCs in this way.  His response was to definitely do this when possible.

**Comment by haussli** [comment]
There have been no opposing comments, so I am assuming that we agree to not duplicating the text.  Please feel free to re-open this if you wish.
